// Code generated by cue extract go. DO NOT EDIT.

//cue:generate cue extract go k8s.io/apimachinery/pkg/watch

// Package watch contains a generic watchable interface, and a fake for
// testing code that uses the watch interface.
package watch
