// Code generated by cue extract go. DO NOT EDIT.

//cue:generate cue extract go k8s.io/apimachinery/pkg/watch

package watch

// FullChannelBehavior controls how the Broadcaster reacts if a watcher's watch
// channel is full.
FullChannelBehavior: int |
WaitIfChannelFull |
DropIfChannelFull

WaitIfChannelFull: 0
DropIfChannelFull: 1
