// Code generated by cue extract go. DO NOT EDIT.

//cue:generate cue extract go github.com/prometheus/common/model

package model

// Fingerprint provides a hash-capable representation of a Metric.
// For our purposes, FNV-1A 64-bit is used.
Fingerprint: uint64

// Fingerprints represents a collection of Fingerprint subject to a given
// natural sorting scheme. It implements sort.Interface.
Fingerprints: [...Fingerprint]
