// Code generated by cue extract go. DO NOT EDIT.

//cue:generate cue extract go github.com/prometheus/common/model

package model

// A Metric is similar to a LabelSet, but the key difference is that a Metric is
// a singleton and refers to one and only one stream of samples.
Metric: LabelSet
