// Code generated by cue extract go. DO NOT EDIT.

//cue:generate cue extract go github.com/prometheus/common/model

// Package model contains common data structures that are shared across
// Prometheus components and libraries.
package model
