apiVersion: v1
kind: Service
metadata:
  name: headchef
  labels:
    app: headchef
    component: kitchen
    domain: prod
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: client
  selector:
    app: headchef
    component: kitchen
    domain: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headchef
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: headchef
        component: kitchen
        domain: prod
      annotations:
        prometheus.io.scrape: "true"
    spec:
      volumes:
      - name: headchef-disk
        gcePersistentDisk:
          pdName: headchef-disk
          fsType: ext4
      - name: secret-headchef
        secret:
          secretName: headchef-secrets
      containers:
      - name: headchef
        image: gcr.io/myproj/headchef:v0.2.16
        volumeMounts:
        - name:  headchef-disk
          mountPath: /logs
        - mountPath: /sslcerts
          name: secret-headchef
          readOnly: true
        ports:
        - containerPort: 8080
        args: [
          "-env=prod",
          "-logdir=/logs",
          "-event-server=events:7788",
        ]
        livenessProbe:
          httpGet:
            path: /debug/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 3