// Code generated by cue extract go. DO NOT EDIT.

//cue:generate cue extract go k8s.io/apimachinery/pkg/types

// Package types implements various generic types used throughout kubernetes.
package types
