// Code generated by cue extract go. DO NOT EDIT.

//cue:generate cue extract go k8s.io/apimachinery/pkg/types

package types

NamespacedName: {
	Namespace: string
	Name:      string
}

Separator: 47 // '/'
