// Code generated by cue extract go. DO NOT EDIT.

//cue:generate cue extract go k8s.io/apimachinery/pkg/apis/meta/v1

package v1

// Duration is a wrapper around time.Duration which supports correct
// marshaling to YAML and JSON. In particular, it marshals into strings, which
// can be used as map keys in json.
Duration: _
