apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
spec:
  replicas: 1
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: watcher
        component: infra
        domain: prod
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: star-example-com-secrets
      containers:
      - name: watcher
        image: gcr.io/myproj/watcher:v0.1.0
        ports:
        - containerPort: 7080
        - containerPort: 7788
        volumeMounts:
          - mountPath: /etc/ssl
            name: secret-volume

