apiVersion: v1
kind: Service
# Our metadata
metadata:
  name: waterdispatcher
  labels:
    app: waterdispatcher
    component: frontend
    domain: prod
spec:
  ports:
  - port: 7080
    targetPort: 7080
    protocol: TCP
    name: http
  selector:
    app: waterdispatcher
    component: frontend
    domain: prod
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: waterdispatcher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: waterdispatcher
        component: frontend
        domain: prod
      annotations:
        prometheus.io.scrape: "true"
        prometheus.io.port: "7080"
    spec:
      containers:
      - name: waterdispatcher
        image: gcr.io/myproj/waterdispatcher:v0.0.48
        ports:
        - containerPort: 7080
        args: [
          "-http=:8080",
          "-etcd=etcd:2379",
        ]

