// Code generated by cue extract go. DO NOT EDIT.

//cue:generate cue extract go k8s.io/apimachinery/pkg/runtime

/*
	Package runtime is a generated protocol buffer package.

	It is generated from these files:
		k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/generated.proto

	It has these top-level messages:
		RawExtension
		TypeMeta
		Unknown
*/
package runtime
