// Code generated by cue extract go. DO NOT EDIT.

//cue:generate cue extract go k8s.io/apimachinery/pkg/api/resource

package resource

// Scale is used for getting and setting the base-10 scaled value.
// Base-2 scales are omitted for mathematical simplicity.
// See Quantity.ScaledValue for more details.
Scale: int32 |
Nano |
Micro |
Milli |
Kilo |
Mega |
Giga |
Tera |
Peta |
Exa

Nano:  -9
Micro: -6
Milli: -3
Kilo:  3
Mega:  6
Giga:  9
Tera:  12
Peta:  15
Exa:   18
