on:
  push:
    branches:
      - master

name: Push to tip
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Rebuild tip.cuelang.org
      run: curl -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.CuelangOrgTipRebuildHook }}

