name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: Run GoReleaser
      uses: docker://goreleaser/goreleaser:latest
      with:
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
